# Config file for automatic testing at travis-ci.org

os:
- linux
language: python
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'

install:
  - pip install tox
  - pip install tox-travis

script:
  - tox

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
