# Config file for automatic testing at travis-ci.org

os:
- linux
language: python
python:
- '2.7'
- '3.5'
- '3.6'

# Travis python3.7 workaround
# See https://github.com/travis-ci/travis-ci/issues/9815
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install tox
  - pip install tox-travis

script:
  - tox

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
